### ISSUE TITLE
Plugin tags broken in newest PaperSpigot version for 1.12.2 (#1613)

### ISSUE THREAD

**Issue by DrakePork** [games647/ColorConsole#6]
After we updated to the newest paperspigot the plugin removed the plugin tags from infront of messages instead of colouring it.
For example it used to do:
[ShopGUIPlus] Person bought from shop

But now it only displays:
Person bought from shop

If I disable or remove the plugin the tag comes back.
Idk if you're still supporting this plugin but can atleast give it a try.

**Comment by games647** [comment]
Could you try the newest build from [here](https://ci.codemc.org/job/Games647/job/ColorConsole/). I did a lot of refactoring. So you also have to regenerate config.

**Comment by DrakePork** [comment]
Eyy it works. Thanks.

**Comment by DrakePork** [comment]
Well I left a message and stuff saying that it worked but then realized that no commands popped up in console, and also this error appeared.

2019-05-02 20:42:04,185 Log4j2-TF-1-AsyncLogger[AsyncContext@1b6d3586]-1 ERROR An exception occurred processing Appender TerminalConsole java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring(String.java:1967)
at com.github.games647.colorconsole.common.CommonFormatter.colorizePluginTag(CommonFormatter.java:80)
at com.github.games647.colorconsole.bukkit.ColorPluginAppender.onAppend(ColorPluginAppender.java:48)
at com.github.games647.colorconsole.common.ColorAppender.append(ColorAppender.java:55)
at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:79)
at org.apache.logging.log4j.core.async.AsyncLogger.actualAsyncLog(AsyncLogger.java:337)
at org.apache.logging.log4j.core.async.RingBufferLogEvent.execute(RingBufferLogEvent.java:161)
at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:45)
at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:29)
at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by games647** [comment]
Yeah I forgot the normal messages. Should be fixed now.

**Comment by DrakePork** [comment]
Huh, seems like it does work but only if you have colorPluginTag: false.
If it's true then it still doesnt work.

**Comment by games647** [comment]
Fixed that in a974dfd859b17648eb12f0b6fcdde5ee96e90eaf

**Comment by DrakePork** [comment]
Yeeeess. Works perfectly now. Thanks alot for fixing it.
